#!/bin/bash

grep "Prolog: "$ $1 &> /dev/null
if [[ $? -eq 0 ]]
then
	echo "You have to complete the 'Lisp: ' line"
	exit 1
fi
grep "Lisp: "$ $1 &> /dev/null
if [[ $? -eq 0 ]]
then
	echo "You have to complete the 'Lisp: ' line"
	exit 1
fi
